version: 2
updates:
  - package-ecosystem: npm #*
    directory: "/" #*
    schedule: #*
      interval: daily
      time: "10:43"
      timezone: Brazil/East

    target-branch: master
    # open-pull-requests-limit: 10
    rebase-strategy: auto
    reviewers:
      - "gbortoloni"
