version: 2
updates:
  - package-ecosystem: npm #*
    directory: "/" #*
    schedule: #*
      interval: daily
      time: "10:35"
      timezone: -03:00 UTC

    target-branch: master
    open-pull-requests-limit: 5
    rebase-strategy: auto
    reviewers:
      - "gbortoloni"
