version: 2
updates:
  - package-ecosystem: npm #*
    directory: "/" #*
    schedule: #*
      interval: daily

    target-branch: master
    open-pull-requests-limit: 5
    rebase-strategy: auto
    reviewers:
      - "gbortoloni"
